### ISSUE TITLE
Problems using Carousel Plug-in

### ISSUE THREAD

**Issue by DaleMFrancis** [twbs/.github#1]
I'm experiencing problems using the Bootstrap Carousel plug-in.  In fact in my project, the Carousel does't work at all (in my project).

This morning I completed substantial additions to the JSFiddle describes the problem, found at https://jsfiddle.net/DaleFrancis/23w0m5k6/20/.  This much-improved JSFiddle should assist greatly in solving the issue. 

If someone will help me with this problem it would be greatly appreciated.  Thank you!

**Comment by DaleMFrancis** [comment]
latest JSFiddle:  https://jsfiddle.net/DaleFrancis/23w0m5k6/33/

**Comment by DaleMFrancis** [comment]
In the JSFiddle, in the 4th quadrant where the site is trying to display, you will see a series of broken links.  These will render as cat pictures.. although not in JSFiddle. This is the Carousel. 

Below this, and below the left/right arrows, you find the descriptions for the currently selected Carousel cat.

**Comment by XhmikosR** [comment]
Unrelated to this repo, though.
